spring.application.name=pedidos
eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka
server.port=0

spring.datasource.url=jdbc:postgresql://localhost:3333/alurafood
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.flyway.enabled=true