CREATE TABLE item_do_pedido (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(255),
  quantidade INTEGER NOT NULL,
  pedido_id BIGINT NOT NULL,
  CONSTRAINT fk_pedido
    FOREIGN KEY (pedido_id)
    REFERENCES pedidos (id)
);